# Site settings
title:          HVHO's devblog
description:    "Terry's portpolio & devblog"
baseurl:        ""
url:            "https://hvho.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Donghyun Kim 
  url:          https://hvho.github.io
  email:        hvho1119@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
  - _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji 

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:     hvhos-devlog

# kramdown setting
# kramdown:
#   hard_wrap: true

# google fonts
# google_fonts: "Nanum+Gothic:400,700"