# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Donghyun Kim
baseurl:        ""
url:            "http://hvho.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Donghyun Kim
  url:          http://hvho.github.io/
  email:        hvho1119@gmail.com
  github:       hvho

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/hvho/HVHO.github.io

